---
- name: Install package
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https

- name: Add docker repo key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install docker packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Removing swap mount
  ansible.posix.mount:
    name: "{{ mounts }}"
    fstype: swap
    state: absent
  vars:
    mounts:
      - swap
      - none

- name: Adding user zen to group docker
  ansible.builtin.user:
    name: zen
    groups: [docker]
    append: true
  become: true
